# Generated by Django 5.2.4 on 2025-11-09 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
