# Generated by Django 5.2.4 on 2025-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g. 10 for 10%)', max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
